# Generated by Django 2.2.3 on 2019-07-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
