# Generated by Django 2.2.3 on 2019-07-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190711_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_name',
            new_name='ingredient',
        ),
    ]
